### ISSUE TITLE
Invalid request

### ISSUE THREAD

**Issue by yimity** [secauth/docs#1]
curl -X GET \
  'https://service-ggnj6gz0-1256804704.ap-hongkong.apigateway.myqcloud.com/release/wxacode?id=558' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXXXXX.eyJhcHBJZCI6IjFfa3hDaiIsImEiOiIwIiwiYiI6Ii0iLCJpYXQiOjE1NzcxNTkyNjUsImV4cCI6MTYwODcxNjXXXXX.OmPJfDJRr6XVVtT040C75wZ6O4FGn8ZMAc9C35XXXXX'

token 后五位 使用了 XXXXX 替换。

返回
{"status":"fail","message":"#74f46db7-2601-11ea-8c0d-52540014ca86: Invalid request"}%

**Comment by secauth** [comment]
是 id 长度检查有问题，已修复。
