### ISSUE TITLE
token will be expired in 1 year?

### ISSUE THREAD

**Issue by zjuchenyuan** [secauth/docs#2]
```
# echo eyJhcHBJZCI6ImdUZWRwZCIsImEiOiIwIiwiYiI6Ii0iLCJpYXQiOjE1NzcyMzQ4MDMsII6MTYwODc5MjQwM30|base64 -d
{"appId":"gTedpd","a":"0","b":"-","iat":1577234803,"exp":1608792403}

# date -d @1608792403
Thu Dec 24 14:46:43 DST 2020
```

do we need to update this token after 1 year?

**Comment by secauth** [comment]
是的，目前 token 有效期是一年，计划做个 API，可以获取最新的 token

**Comment by secauth** [comment]
设置有效期主要是安全考虑，不过要手动更新确实会造成一定不便，目前还有个想法就是设置 IP 白名单然后获得长效 token，希望有人能给点建议，探讨下如何实现更好。

主要问题是在于数据库在小程序端，外部没法访问，生成小程序码这端没法判定 token 的状态。

**Comment by xiao-nz** [comment]
jwt 没有一年这么长的吧？

**Comment by secauth** [comment]
@xiaoyanbot 我也不希望有效期这么长，目前似乎只能这样。
