### ISSUE TITLE
登录出错

### ISSUE THREAD

**Issue by yimity** [secauth/docs#3]
1. [XXX] 连接失败，请稍后重试。
哪里可以看到错误的日志？

2. 应用的回调地址经常丢失。
设置好了，再去看，就不见了。

**Comment by secauth** [comment]
1. 计划加入测试，方便调试，目前只能我来协助，刚看了日志，应该是返回格式有误，需要返回 JSON。
2. 已修复。

**Comment by secauth** [comment]
需要按此格式返回登录结果
```
Content-Type: application/json

{
  status: 'success' // 登录成功
}
```

**Comment by secauth** [comment]
新版本可以测试了，目前审核中，有需要的可以使用体验版：

![安全登录体验版邀请](https://user-images.githubusercontent.com/59008726/71465516-d4463e00-27f7-11ea-804f-51d9ddfe34ba.png)
